server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      routes:
        - id: video-service
          uri: lb://VIDEO-SERVICE
          predicates:
            - Path=/api/videos/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
